"""Reality Mesh -- typed handoff substrate for Phase 012 (IMPLEMENTATION-012A).

The frozen, label-only, provenance/conflict/gap-preserving objects that flow between agents,
synthesizers, and layers in the Real-Time Reality Intelligence Sensor Mesh, plus the closed
label vocabularies and validation guards that keep them honest.

This slice is INFRASTRUCTURE ONLY: typed contracts + closed vocabularies + validation +
tests. There are NO agents, NO reasoning, NO scheduler / streaming / broker / trading /
scoring here. Every object is:

* **labels, not numbers** -- no numeric investability / score / rank / rating field, and no
  buy / sell / hold / order / trade / broker field anywhere;
* **evidence-preserving** -- ``source_refs`` / ``evidence_refs``, ``conflicts`` and
  ``data_gaps`` carried end-to-end; missing -> explicit gap, never a fabricated value;
* **frozen + validated on construction** -- closed labels only; empty required id rejected;
  X/social never a verified fact; manual/analyst never canonical.

Deterministic, stdlib-only, Python 3.9. No network on import; no scheduler / broker; every
timestamp is an injected string (no wall-clock in any id/replay path).
"""

from __future__ import annotations

from .labels import (
    ALLOWED_DOWNSTREAM_USES,
    CLAIM_STATUSES,
    CONFIDENCE_LABELS,
    CONTRADICTION_STATUSES,
    CORROBORATION_STATUSES,
    DEFAULT_FORBIDDEN_DOWNSTREAM_USES,
    DIRECTION_LABELS,
    DISCIPLINES,
    FORBIDDEN_DOWNSTREAM_USES,
    FRESHNESS_LABELS,
    HALF_LIFE_LABELS,
    LAYERS,
    LAYER_DISPLAY,
    LEGACY_LAYER_ALIASES,
    MAGNITUDE_LABELS,
    PAYLOAD_TYPES,
    ROUTING_TARGETS,
    SOURCE_AUTHORITIES,
    THEME_PULSE_STATES,
    URGENCY_LABELS,
    authority_rank,
    is_claim_status,
    is_discipline,
    is_member,
    is_social_source,
    is_source_authority,
    is_theme_pulse_state,
    normalize_layer,
    ordered_authorities,
)
from .models import (
    CORE_MODELS,
    AgentFinding,
    DiligenceInputBundle,
    HandoffEnvelope,
    OpportunityHypothesisPacket,
    RealityEvent,
    RealitySignal,
    SignalCluster,
    ThemePulse,
)
from .validation import (
    TRADE_FIELD_TOKENS,
    assert_evidence_preserved,
    assert_manual_not_canonical,
    assert_no_trade_fields,
    assert_required_ids,
    assert_social_not_verified,
    validate_envelope,
    validate_event,
    validate_finding,
    validate_labels,
    validate_signal,
    validate_theme_pulse,
)
from .agents import (
    AGENT_TYPES,
    LAYER_ALLOWED_EMITS,
    LAYER_FORBIDDEN_EMITS,
    MANDATORY_FORBIDDEN_OUTPUTS,
    TATTVA_FINDING_SUBTYPES,
    AgentDescriptor,
    SensorAgent,
    validate_descriptor,
)
from .registry import (
    DEFAULT_DESCRIPTORS,
    AgentRegistry,
    build_default_registry,
)
from .router import BuddhiRouter, IntelligenceGovernanceRouter
from .fusion import (
    FusionResult,
    RealityIntelligenceSignalFusion,
    TattvaSignalFusionSynthesizer,
)
from .sphurana import OpportunityDiscoveryResult, SphuranaResult, ThemePulseSynthesizer
from .render_adapters import (
    build_pulse_data_quality_panel,
    build_run_observability_panel,
)
from .pulse import (
    DEFAULT_PULSE_FIXTURE_DIR,
    PulseAgentRun,
    PulseResult,
    run_pulse,
)
from .sensors import (
    MARKET_REGIME_FINDING_TYPES,
    MARKET_REGIME_SUBAGENTS,
    MarketRegimeAgent,
    events_from_fixture,
    SectorRotationAgent,
    ThemeRotationAgent,
    SECTOR_ROTATION_FINDING_TYPES,
    SECTOR_ROTATION_SUBAGENTS,
    THEME_ROTATION_FINDING_TYPES,
    THEME_ROTATION_SUBAGENTS,
    FLOW_PROXY_CAVEAT,
    BROADENING_MIN_MEMBERS,
    NewsFilingsAgent,
    NEWS_FILINGS_FINDING_TYPES,
    NEWS_FILINGS_SUBAGENTS,
    FILING_FACT_FINDINGS,
    COMPANY_CLAIM_FINDINGS,
    claim_status_of,
    SocialNarrativeAgent,
    SOCIAL_NARRATIVE_FINDING_TYPES,
    SOCIAL_NARRATIVE_SUBAGENTS,
    assert_narrative_not_verified,
)
from .runtime import (
    RUNTIME_OBJECTS,
    AgentHealthRecord,
    AgentRunContext,
    AgentRunResult,
    PulseRun,
    ReplayRequest,
    ReplayResult,
)
from .labels import (
    AGENT_RUN_STATUSES,
    ALLOWED_TRIGGER_TYPES,
    DATA_QUALITY_STATUSES,
    HEALTH_STATES,
    RESERVED_TRIGGER_TYPES,
    RUN_MODES,
    RUN_STATUSES,
    TRIGGER_TYPES,
    is_agent_run_status,
    is_health_state,
    is_reserved_trigger_type,
    is_run_mode,
    is_run_status,
    is_trigger_type,
)
from .stores import (
    SCHEMA_VERSION,
    CREDENTIAL_KEY_TOKENS,
    FORBIDDEN_FIELD_TOKENS,
    DQ_STATUSES,
    DataQualityRecord,
    AuditRecord,
    AppendOnlyStore,
    RunStore,
    EventStore,
    FindingStore,
    SignalStore,
    ThemePulseStore,
    DataQualityStore,
    AuditStore,
    STORE_CLASSES,
)
from .replay import (
    ReplayHarness,
    ReplayReconstruction,
)
from .pulse_persistence import (
    PULSE_FIXTURE_SOURCE_ID,
    agent_results_from_pulse,
    persist_and_summarize,
)
from .ledger import (
    AgentRunLedger,
    PolicyBlock,
    POLICY_MESSAGE_TOKENS,
    SkipAgent,
    run_agent_isolated,
    run_agents_isolated,
)
from .health import (
    CREDENTIALS_STATUSES,
    RATE_LIMIT_STATUSES,
    AgentHealthMonitor,
    DataQualityRunSummary,
    HEALTH_RECORDS,
    RunHealthSummary,
    SourceHealthRecord,
)
from .gates import (
    GATE_CATEGORIES,
    GATE_STATUSES,
    POLICY_OR_SECURITY_CATEGORIES,
    REAL_DATA_MODES,
    NETWORK_IMPORT_ROOTS,
    SCHEDULER_BROKER_SOURCE_TOKENS,
    SECRET_VALUE_PATTERNS,
    FORBIDDEN_RECORD_FIELD_WORDS,
    DataQualityGateResult,
    SecurityGateResult,
    PolicyGateResult,
    DataQualityGateRunner,
)
from .adapters import (
    ADAPTER_CREDENTIALS_STATUSES,
    ADAPTER_FAILURE_MODES,
    ADAPTER_RATE_LIMIT_STATUSES,
    ADAPTER_RESULT_STATUSES,
    ADAPTER_SOURCE_HEALTH_LABELS,
    LOCAL_MARKET_DATA_ADAPTER_ID,
    LOCAL_MARKET_DATA_DESCRIPTOR,
    LOCAL_MARKET_DATA_DISCIPLINES,
    LOCAL_MARKET_DATA_FILES,
    STALE_AFTER_HOURS,
    LocalMarketDataAdapter,
    SourceAdapter,
    SourceAdapterDescriptor,
    SourceAdapterResult,
    deterministic_adapter_run_id,
    source_health_from_result,
)
from .nivesha_forward import (
    FORWARD_INPUT_NAMES,
    SCENARIO_LABELS,
    ForwardScenarioInput,
    ForwardScenarioCase,
    ForwardScenarioPacket,
    ForwardMappedField,
    ForwardSidecarMapping,
    build_forward_scenario_packet,
    to_nivesha_forward_sidecar,
    run_nivesha_thesis_on_forward_sidecar,
)

__all__ = [
    # models
    "RealityEvent",
    "AgentFinding",
    "HandoffEnvelope",
    "RealitySignal",
    "SignalCluster",
    "ThemePulse",
    "OpportunityHypothesisPacket",
    "DiligenceInputBundle",
    "CORE_MODELS",
    # label vocabularies
    "SOURCE_AUTHORITIES",
    "CLAIM_STATUSES",
    "DISCIPLINES",
    "DIRECTION_LABELS",
    "MAGNITUDE_LABELS",
    "URGENCY_LABELS",
    "CONFIDENCE_LABELS",
    "FRESHNESS_LABELS",
    "HALF_LIFE_LABELS",
    "CORROBORATION_STATUSES",
    "CONTRADICTION_STATUSES",
    "THEME_PULSE_STATES",
    "LAYERS",
    "LAYER_DISPLAY",
    "LEGACY_LAYER_ALIASES",
    "normalize_layer",
    "ROUTING_TARGETS",
    "PAYLOAD_TYPES",
    "ALLOWED_DOWNSTREAM_USES",
    "FORBIDDEN_DOWNSTREAM_USES",
    "DEFAULT_FORBIDDEN_DOWNSTREAM_USES",
    # label helpers
    "is_member",
    "is_source_authority",
    "is_claim_status",
    "is_discipline",
    "is_theme_pulse_state",
    "is_social_source",
    "ordered_authorities",
    "authority_rank",
    # validation
    "TRADE_FIELD_TOKENS",
    "assert_no_trade_fields",
    "assert_manual_not_canonical",
    "assert_social_not_verified",
    "assert_required_ids",
    "assert_evidence_preserved",
    "validate_labels",
    "validate_event",
    "validate_finding",
    "validate_signal",
    "validate_theme_pulse",
    "validate_envelope",
    # agents / registry / router (012B)
    "AgentDescriptor",
    "SensorAgent",
    "validate_descriptor",
    "AGENT_TYPES",
    "TATTVA_FINDING_SUBTYPES",
    "LAYER_ALLOWED_EMITS",
    "LAYER_FORBIDDEN_EMITS",
    "MANDATORY_FORBIDDEN_OUTPUTS",
    "AgentRegistry",
    "build_default_registry",
    "DEFAULT_DESCRIPTORS",
    "BuddhiRouter",
    "IntelligenceGovernanceRouter",
    # fusion synthesizer (012C)
    "TattvaSignalFusionSynthesizer",
    "RealityIntelligenceSignalFusion",
    "FusionResult",
    # sphurana theme-pulse synthesizer (012F)
    "ThemePulseSynthesizer",
    "SphuranaResult",
    "OpportunityDiscoveryResult",
    # sensor agents (012D)
    "MarketRegimeAgent",
    "MARKET_REGIME_FINDING_TYPES",
    "MARKET_REGIME_SUBAGENTS",
    "events_from_fixture",
    # sensor agents (012E)
    "SectorRotationAgent",
    "ThemeRotationAgent",
    "SECTOR_ROTATION_FINDING_TYPES",
    "SECTOR_ROTATION_SUBAGENTS",
    "THEME_ROTATION_FINDING_TYPES",
    "THEME_ROTATION_SUBAGENTS",
    "FLOW_PROXY_CAVEAT",
    "BROADENING_MIN_MEMBERS",
    # sensor agents (012G)
    "NewsFilingsAgent",
    "NEWS_FILINGS_FINDING_TYPES",
    "NEWS_FILINGS_SUBAGENTS",
    "FILING_FACT_FINDINGS",
    "COMPANY_CLAIM_FINDINGS",
    "claim_status_of",
    # sensor agents (012H)
    "SocialNarrativeAgent",
    "SOCIAL_NARRATIVE_FINDING_TYPES",
    "SOCIAL_NARRATIVE_SUBAGENTS",
    "assert_narrative_not_verified",
    # forward scenario engine / sidecar (012I)
    "FORWARD_INPUT_NAMES",
    "SCENARIO_LABELS",
    "ForwardScenarioInput",
    "ForwardScenarioCase",
    "ForwardScenarioPacket",
    "ForwardMappedField",
    "ForwardSidecarMapping",
    "build_forward_scenario_packet",
    "to_nivesha_forward_sidecar",
    "run_nivesha_thesis_on_forward_sidecar",
    # data-quality / universe signal integration (012J)
    "build_pulse_data_quality_panel",
    "build_run_observability_panel",
    # manual/on-demand pulse orchestrator (012K)
    "run_pulse",
    "PulseResult",
    "PulseAgentRun",
    "DEFAULT_PULSE_FIXTURE_DIR",
    # runtime objects (013A)
    "PulseRun",
    "AgentRunContext",
    "AgentRunResult",
    "AgentHealthRecord",
    "ReplayRequest",
    "ReplayResult",
    "RUNTIME_OBJECTS",
    # runtime label vocabularies (013A)
    "RUN_MODES",
    "TRIGGER_TYPES",
    "ALLOWED_TRIGGER_TYPES",
    "RESERVED_TRIGGER_TYPES",
    "RUN_STATUSES",
    "DATA_QUALITY_STATUSES",
    "AGENT_RUN_STATUSES",
    "HEALTH_STATES",
    # runtime label helpers (013A)
    "is_run_mode",
    "is_trigger_type",
    "is_reserved_trigger_type",
    "is_run_status",
    "is_agent_run_status",
    "is_health_state",
    # append-only persistence stores (013B)
    "SCHEMA_VERSION",
    "CREDENTIAL_KEY_TOKENS",
    "FORBIDDEN_FIELD_TOKENS",
    "DQ_STATUSES",
    "DataQualityRecord",
    "AuditRecord",
    "AppendOnlyStore",
    "RunStore",
    "EventStore",
    "FindingStore",
    "SignalStore",
    "ThemePulseStore",
    "DataQualityStore",
    "AuditStore",
    "STORE_CLASSES",
    # deterministic replay harness (013C)
    "ReplayHarness",
    "ReplayReconstruction",
    # pulse persistence + observability glue (013F)
    "PULSE_FIXTURE_SOURCE_ID",
    "agent_results_from_pulse",
    "persist_and_summarize",
    # agent run ledger + failure-isolating runner (013D)
    "AgentRunLedger",
    "run_agent_isolated",
    "run_agents_isolated",
    "SkipAgent",
    "PolicyBlock",
    "POLICY_MESSAGE_TOKENS",
    # health / data-quality observability (013D)
    "SourceHealthRecord",
    "RunHealthSummary",
    "DataQualityRunSummary",
    "AgentHealthMonitor",
    "HEALTH_RECORDS",
    "CREDENTIALS_STATUSES",
    "RATE_LIMIT_STATUSES",
    # data-quality / security / policy gate runner (013E)
    "GATE_CATEGORIES",
    "GATE_STATUSES",
    "POLICY_OR_SECURITY_CATEGORIES",
    "REAL_DATA_MODES",
    "NETWORK_IMPORT_ROOTS",
    "SCHEDULER_BROKER_SOURCE_TOKENS",
    "SECRET_VALUE_PATTERNS",
    "FORBIDDEN_RECORD_FIELD_WORDS",
    "DataQualityGateResult",
    "SecurityGateResult",
    "PolicyGateResult",
    "DataQualityGateRunner",
    # source-adapter runtime + local market-data adapter (014A)
    "ADAPTER_RESULT_STATUSES",
    "ADAPTER_CREDENTIALS_STATUSES",
    "ADAPTER_RATE_LIMIT_STATUSES",
    "ADAPTER_FAILURE_MODES",
    "ADAPTER_SOURCE_HEALTH_LABELS",
    "SourceAdapterDescriptor",
    "SourceAdapterResult",
    "SourceAdapter",
    "deterministic_adapter_run_id",
    "source_health_from_result",
    "LOCAL_MARKET_DATA_ADAPTER_ID",
    "LOCAL_MARKET_DATA_DESCRIPTOR",
    "LOCAL_MARKET_DATA_DISCIPLINES",
    "LOCAL_MARKET_DATA_FILES",
    "STALE_AFTER_HOURS",
    "LocalMarketDataAdapter",
]
