"""Reality Mesh -- typed handoff substrate for Phase 012 (IMPLEMENTATION-012A).

The frozen, label-only, provenance/conflict/gap-preserving objects that flow between agents,
synthesizers, and layers in the Real-Time Reality Intelligence Sensor Mesh, plus the closed
label vocabularies and validation guards that keep them honest.

This slice is INFRASTRUCTURE ONLY: typed contracts + closed vocabularies + validation +
tests. There are NO agents, NO reasoning, NO scheduler / streaming / broker / trading /
scoring here. Every object is:

* **labels, not numbers** -- no numeric investability / score / rank / rating field, and no
  buy / sell / hold / order / trade / broker field anywhere;
* **evidence-preserving** -- ``source_refs`` / ``evidence_refs``, ``conflicts`` and
  ``data_gaps`` carried end-to-end; missing -> explicit gap, never a fabricated value;
* **frozen + validated on construction** -- closed labels only; empty required id rejected;
  X/social never a verified fact; manual/analyst never canonical.

Deterministic, stdlib-only, Python 3.9. No network on import; no scheduler / broker; every
timestamp is an injected string (no wall-clock in any id/replay path).
"""

from __future__ import annotations

from .labels import (
    ALLOWED_DOWNSTREAM_USES,
    CLAIM_STATUSES,
    CONFIDENCE_LABELS,
    CONTRADICTION_STATUSES,
    CORROBORATION_STATUSES,
    DEFAULT_FORBIDDEN_DOWNSTREAM_USES,
    DIRECTION_LABELS,
    DISCIPLINES,
    FORBIDDEN_DOWNSTREAM_USES,
    FRESHNESS_LABELS,
    HALF_LIFE_LABELS,
    LAYERS,
    LAYER_DISPLAY,
    LEGACY_LAYER_ALIASES,
    MAGNITUDE_LABELS,
    PAYLOAD_TYPES,
    ROUTING_TARGETS,
    SOURCE_AUTHORITIES,
    THEME_PULSE_STATES,
    URGENCY_LABELS,
    authority_rank,
    is_claim_status,
    is_discipline,
    is_member,
    is_social_source,
    is_source_authority,
    is_theme_pulse_state,
    normalize_layer,
    ordered_authorities,
)
from .models import (
    CORE_MODELS,
    AgentFinding,
    DiligenceInputBundle,
    HandoffEnvelope,
    OpportunityHypothesisPacket,
    RealityEvent,
    RealitySignal,
    SignalCluster,
    ThemePulse,
)
from .validation import (
    TRADE_FIELD_TOKENS,
    assert_evidence_preserved,
    assert_manual_not_canonical,
    assert_no_trade_fields,
    assert_required_ids,
    assert_social_not_verified,
    validate_envelope,
    validate_event,
    validate_finding,
    validate_labels,
    validate_signal,
    validate_theme_pulse,
)
from .agents import (
    AGENT_TYPES,
    LAYER_ALLOWED_EMITS,
    LAYER_FORBIDDEN_EMITS,
    MANDATORY_FORBIDDEN_OUTPUTS,
    TATTVA_FINDING_SUBTYPES,
    AgentDescriptor,
    SensorAgent,
    validate_descriptor,
)
from .registry import (
    DEFAULT_DESCRIPTORS,
    AgentRegistry,
    build_default_registry,
)
from .router import BuddhiRouter, IntelligenceGovernanceRouter
from .fusion import (
    FusionResult,
    RealityIntelligenceSignalFusion,
    TattvaSignalFusionSynthesizer,
)
from .sphurana import OpportunityDiscoveryResult, SphuranaResult, ThemePulseSynthesizer
from .render_adapters import (
    build_alert_inbox_panel,
    build_pulse_data_quality_panel,
    build_run_observability_panel,
)
from .pulse import (
    DEFAULT_PULSE_FIXTURE_DIR,
    PulseAgentRun,
    PulseResult,
    run_pulse,
)
from .sensors import (
    MARKET_REGIME_FINDING_TYPES,
    MARKET_REGIME_SUBAGENTS,
    MarketRegimeAgent,
    events_from_fixture,
    SectorRotationAgent,
    ThemeRotationAgent,
    SECTOR_ROTATION_FINDING_TYPES,
    SECTOR_ROTATION_SUBAGENTS,
    THEME_ROTATION_FINDING_TYPES,
    THEME_ROTATION_SUBAGENTS,
    FLOW_PROXY_CAVEAT,
    BROADENING_MIN_MEMBERS,
    NewsFilingsAgent,
    NEWS_FILINGS_FINDING_TYPES,
    NEWS_FILINGS_SUBAGENTS,
    FILING_FACT_FINDINGS,
    COMPANY_CLAIM_FINDINGS,
    claim_status_of,
    SocialNarrativeAgent,
    SOCIAL_NARRATIVE_FINDING_TYPES,
    SOCIAL_NARRATIVE_SUBAGENTS,
    assert_narrative_not_verified,
    TechnicalRegimeAgent,
    TECHNICAL_REGIME_FINDING_TYPES,
    TECHNICAL_REGIME_SUBAGENTS,
    TECHNICAL_SUBAGENT_REQUIRED_KEYS,
    COMPRESSION_MAX_RANGE_PCT,
    OVEREXTENSION_MIN_PCT,
    VOLUME_CONFIRM_MULT,
    MacroRegimeAgent,
    MACRO_REGIME_FINDING_TYPES,
    MACRO_REGIME_SUBAGENTS,
    MACRO_SUBAGENT_REQUIRED_KEYS,
    CustomerEvidenceAgent,
    SupplierEvidenceAgent,
    BottleneckEvidenceAgent,
    LeadershipEvidenceAgent,
    CUSTOMER_EVIDENCE_FINDING_TYPES,
    SUPPLIER_EVIDENCE_FINDING_TYPES,
    BOTTLENECK_EVIDENCE_FINDING_TYPES,
    LEADERSHIP_EVIDENCE_FINDING_TYPES,
    COMPANY_DOCUMENT_TEXT_EVENT_TYPES,
    COMPANY_STATED_CAPACITY_GAP,
    has_bottleneck_evidence_events,
)
from .runtime import (
    RUNTIME_OBJECTS,
    AgentHealthRecord,
    AgentRunContext,
    AgentRunResult,
    PulseRun,
    ReplayRequest,
    ReplayResult,
)
from .labels import (
    AGENT_RUN_STATUSES,
    ALLOWED_TRIGGER_TYPES,
    DATA_QUALITY_STATUSES,
    HEALTH_STATES,
    RESERVED_TRIGGER_TYPES,
    RUN_MODES,
    RUN_STATUSES,
    TRIGGER_TYPES,
    is_agent_run_status,
    is_health_state,
    is_reserved_trigger_type,
    is_run_mode,
    is_run_status,
    is_trigger_type,
)
from .stores import (
    SCHEMA_VERSION,
    CREDENTIAL_KEY_TOKENS,
    FORBIDDEN_FIELD_TOKENS,
    DQ_STATUSES,
    DataQualityRecord,
    AuditRecord,
    AppendOnlyStore,
    RunStore,
    EventStore,
    FindingStore,
    SignalStore,
    ThemePulseStore,
    DataQualityStore,
    AuditStore,
    STORE_CLASSES,
)
from .replay import (
    ReplayHarness,
    ReplayReconstruction,
)
from .pulse_persistence import (
    PULSE_FIXTURE_SOURCE_ID,
    agent_results_from_pulse,
    persist_and_summarize,
)
from .ledger import (
    AgentRunLedger,
    PolicyBlock,
    POLICY_MESSAGE_TOKENS,
    SkipAgent,
    run_agent_isolated,
    run_agents_isolated,
)
from .health import (
    CREDENTIALS_STATUSES,
    RATE_LIMIT_STATUSES,
    AgentHealthMonitor,
    DataQualityRunSummary,
    HEALTH_RECORDS,
    RunHealthSummary,
    SourceHealthRecord,
)
from .gates import (
    GATE_CATEGORIES,
    GATE_STATUSES,
    POLICY_OR_SECURITY_CATEGORIES,
    REAL_DATA_MODES,
    NETWORK_IMPORT_ROOTS,
    SCHEDULER_BROKER_SOURCE_TOKENS,
    SECRET_VALUE_PATTERNS,
    FORBIDDEN_RECORD_FIELD_WORDS,
    DataQualityGateResult,
    SecurityGateResult,
    PolicyGateResult,
    DataQualityGateRunner,
)
from .capital_candidate import (
    CANDIDATE_STATES,
    CAPITAL_CANDIDATE_MODELS,
    FORWARD_SCENARIO_STATES,
    INELIGIBLE_STATES,
    TRUST_DATA_QUALITY_STATES,
    CapitalCandidate,
    CapitalCandidateStore,
    assess_candidate_eligibility,
    blocked_candidates,
    candidate_id_for,
    eligible_candidates,
    publish_candidates_for_run,
    published_candidates,
)
from .adapters import (
    ADAPTER_CREDENTIALS_STATUSES,
    ADAPTER_FAILURE_MODES,
    ADAPTER_RATE_LIMIT_STATUSES,
    ADAPTER_RESULT_STATUSES,
    ADAPTER_SOURCE_HEALTH_LABELS,
    COMPANY_DOCUMENTS_ADAPTER_ID,
    COMPANY_DOCUMENTS_DESCRIPTOR,
    COMPANY_DOCUMENTS_DISCIPLINES,
    DESCRIPTOR_ONLY_CONSUMER_GAPS,
    DOCUMENT_STALE_AFTER_DAYS,
    FINANCIAL_INFLECTION_CONSUMER_GAP,
    FMP_TRANSPORT_KEYS,
    IR_DECK_FILENAMES,
    LOCAL_MACRO_DATA_ADAPTER_ID,
    LOCAL_MACRO_DATA_DESCRIPTOR,
    LOCAL_MACRO_DATA_DISCIPLINES,
    MACRO_READINGS_FILENAME,
    MACRO_STALE_AFTER_HOURS,
    LocalMacroDataAdapter,
    LOCAL_MARKET_DATA_ADAPTER_ID,
    LOCAL_MARKET_DATA_DESCRIPTOR,
    LOCAL_MARKET_DATA_DISCIPLINES,
    LOCAL_MARKET_DATA_FILES,
    LOCAL_PRICE_HISTORY_ADAPTER_ID,
    LOCAL_PRICE_HISTORY_DESCRIPTOR,
    LOCAL_PRICE_HISTORY_DISCIPLINES,
    PRICE_HISTORY_FILE_SUFFIX,
    PRICE_HISTORY_INDICATOR_UNITS,
    PRICE_HISTORY_STALE_AFTER_HOURS,
    LocalPriceHistoryAdapter,
    PROMOTER_BOT_RISK_VISIBLE_PCT,
    SEC_EDGAR_LIVE_ADAPTER_ID,
    SEC_EDGAR_LIVE_DESCRIPTOR,
    SEC_EDGAR_LIVE_DISCIPLINES,
    SEC_EDGAR_LIVE_EVENT_TYPES,
    SEC_EDGAR_LIVE_FULL_BODY_FOLLOWUP_GAP,
    SEC_EDGAR_LIVE_MINIMUM_FORMS,
    SEC_EDGAR_LIVE_RISK_EVENT_TYPES,
    SEC_EDGAR_LIVE_TRANSPORT_KEYS,
    SecEdgarLiveAdapter,
    SEC_FMP_EVIDENCE_ADAPTER_ID,
    SEC_FMP_EVIDENCE_DESCRIPTOR,
    SEC_FMP_EVIDENCE_DISCIPLINES,
    SEC_TRANSPORT_KEYS,
    SOCIAL_EXPORT_ACCOUNT_TYPES,
    SOCIAL_EXPORT_FILE_PREFIX,
    SOCIAL_EXPORT_STALE_AFTER_HOURS,
    SOCIAL_EXPORTS_ADAPTER_ID,
    SOCIAL_EXPORTS_DESCRIPTOR,
    SOCIAL_EXPORTS_DISCIPLINES,
    STALE_AFTER_HOURS,
    TAM_NOT_INDEPENDENTLY_VERIFIED_GAP,
    TRANSCRIPT_FILE_PREFIX,
    CompanyDocumentsAdapter,
    LocalMarketDataAdapter,
    SecFmpEvidenceAdapter,
    SocialExportsAdapter,
    SourceAdapter,
    SourceAdapterDescriptor,
    SourceAdapterResult,
    deterministic_adapter_run_id,
    source_health_from_result,
)
from .scheduler import (
    ALL_POLICIES,
    DEFAULT_CADENCE_POLICIES,
    DEFAULT_MARKET_HOURS,
    MAX_BACKOFF_MINUTES,
    THROTTLE_WINDOW_MINUTES,
    CadencePolicy,
    MarketHoursCalendar,
    PulseSchedule,
    ScheduleState,
    build_default_schedule,
    calendar_from_dict,
    calendar_to_dict,
    due_policies,
    pause,
    policy_from_dict,
    policy_to_dict,
    record_run,
    resume,
    schedule_from_dict,
    schedule_to_dict,
    state_for,
    state_from_dict,
    state_to_dict,
    throttled,
)
from .orchestrator import (
    ORCHESTRATOR_ACTOR,
    SCHEDULED_BY_POLICY_PREFIX,
    PulseOrchestrator,
    ScheduleStateStore,
    Subscription,
    TickResult,
    append_schedule_state,
    load_schedule_state,
    run_due_pulses,
    scheduled_policy_for,
    subscription_from_dict,
    subscription_to_dict,
)
from .alerts import (
    ALERT_CATEGORIES,
    ALERT_SEVERITIES,
    CATEGORY_SEVERITY,
    FORBIDDEN_ALERT_PHRASES,
    RECOMMENDED_REVIEW_ACTIONS,
    SHADOW_MARKER,
    SHADOW_MODE_VALUE,
    Alert,
    AlertAcknowledgment,
    AlertAcknowledgmentStore,
    AlertGenerationResult,
    AlertStore,
    acknowledge_alert,
    acknowledged_alert_ids,
    acknowledged_alerts,
    alerts_with_status,
    diff_persisted_runs,
    generate_alerts_for_run,
    generate_shadow_alerts_for_run,
    previous_persisted_run_id,
    record_failed_pulse_alert,
    run_dq_state,
    to_shadow,
    unacknowledged_alerts,
)
from .nivesha_forward import (
    FORWARD_INPUT_NAMES,
    SCENARIO_LABELS,
    ForwardScenarioInput,
    ForwardScenarioCase,
    ForwardScenarioPacket,
    ForwardMappedField,
    ForwardSidecarMapping,
    build_forward_scenario_packet,
    to_nivesha_forward_sidecar,
    run_nivesha_thesis_on_forward_sidecar,
)
from .learning import (
    LEARNING_RECORDS,
    LEARNING_STORE_CLASSES,
    LEARNING_THRESHOLDS,
    OUTCOME_LABELS,
    RELIABILITY_LABELS,
    RISK_CLAIM_STATES,
    SUBJECT_KINDS,
    LearningStore,
    OutcomeRecord,
    OutcomeStore,
    OutcomeTracker,
    SignalReliabilityRecord,
    SourceReliabilityRecord,
    ThemePulseAccuracyRecord,
    emit_outcome_alerts,
    persisted_run_ids,
    record_learning_rollups,
    record_outcomes,
    roll_signal_reliability,
    roll_source_reliability,
    roll_theme_pulse_accuracy,
    track_outcomes,
)
from .portfolio import (
    BAND_UNKNOWN,
    CANDIDATE_COMPARISON_LABELS,
    CONCENTRATION_BANDS,
    CORRELATION_LABELS,
    HOLDINGS_FILENAME,
    HOLDINGS_FRESHNESS_LABELS,
    HOLDINGS_RELPATH,
    PORTFOLIO_DIRNAME,
    PORTFOLIO_RECORDS,
    PORTFOLIO_THRESHOLDS,
    ROTATION_ALIGNMENT_LABELS,
    STATE_ALIGNMENT,
    CandidateComparison,
    ConcentrationView,
    ExposureView,
    HoldingRecord,
    PairCorrelationView,
    PortfolioHoldings,
    RotationAlignmentView,
    band_for_position_weight,
    band_for_theme_weight,
    build_concentration,
    build_correlation_labels,
    build_exposure,
    build_rotation_alignment,
    compare_candidate,
    load_holdings,
    ticker_theme_map,
)
from .reviews import (
    JOURNAL_VERDICTS,
    POSTMORTEM_LABELS,
    REVIEW_RECORDS,
    REVIEW_THRESHOLDS,
    TIMING_CLAIMS,
    TIMING_LABELS,
    ArchetypeUpdate,
    ExperienceLayerUpdate,
    ExpertAccountReliabilityRecord,
    RedTeamReview,
    ThesisJournalEntry,
    ThesisJournalStore,
    ThesisPostmortem,
    TimingReview,
    append_experience_update,
    journal_thesis,
    review_red_team,
    review_thesis,
    review_timing,
    roll_archetypes,
    roll_expert_reliability,
)

__all__ = [
    # models
    "RealityEvent",
    "AgentFinding",
    "HandoffEnvelope",
    "RealitySignal",
    "SignalCluster",
    "ThemePulse",
    "OpportunityHypothesisPacket",
    "DiligenceInputBundle",
    "CORE_MODELS",
    # label vocabularies
    "SOURCE_AUTHORITIES",
    "CLAIM_STATUSES",
    "DISCIPLINES",
    "DIRECTION_LABELS",
    "MAGNITUDE_LABELS",
    "URGENCY_LABELS",
    "CONFIDENCE_LABELS",
    "FRESHNESS_LABELS",
    "HALF_LIFE_LABELS",
    "CORROBORATION_STATUSES",
    "CONTRADICTION_STATUSES",
    "THEME_PULSE_STATES",
    "LAYERS",
    "LAYER_DISPLAY",
    "LEGACY_LAYER_ALIASES",
    "normalize_layer",
    "ROUTING_TARGETS",
    "PAYLOAD_TYPES",
    "ALLOWED_DOWNSTREAM_USES",
    "FORBIDDEN_DOWNSTREAM_USES",
    "DEFAULT_FORBIDDEN_DOWNSTREAM_USES",
    # label helpers
    "is_member",
    "is_source_authority",
    "is_claim_status",
    "is_discipline",
    "is_theme_pulse_state",
    "is_social_source",
    "ordered_authorities",
    "authority_rank",
    # validation
    "TRADE_FIELD_TOKENS",
    "assert_no_trade_fields",
    "assert_manual_not_canonical",
    "assert_social_not_verified",
    "assert_required_ids",
    "assert_evidence_preserved",
    "validate_labels",
    "validate_event",
    "validate_finding",
    "validate_signal",
    "validate_theme_pulse",
    "validate_envelope",
    # agents / registry / router (012B)
    "AgentDescriptor",
    "SensorAgent",
    "validate_descriptor",
    "AGENT_TYPES",
    "TATTVA_FINDING_SUBTYPES",
    "LAYER_ALLOWED_EMITS",
    "LAYER_FORBIDDEN_EMITS",
    "MANDATORY_FORBIDDEN_OUTPUTS",
    "AgentRegistry",
    "build_default_registry",
    "DEFAULT_DESCRIPTORS",
    "BuddhiRouter",
    "IntelligenceGovernanceRouter",
    # fusion synthesizer (012C)
    "TattvaSignalFusionSynthesizer",
    "RealityIntelligenceSignalFusion",
    "FusionResult",
    # sphurana theme-pulse synthesizer (012F)
    "ThemePulseSynthesizer",
    "SphuranaResult",
    "OpportunityDiscoveryResult",
    # sensor agents (012D)
    "MarketRegimeAgent",
    "MARKET_REGIME_FINDING_TYPES",
    "MARKET_REGIME_SUBAGENTS",
    "events_from_fixture",
    # sensor agents (012E)
    "SectorRotationAgent",
    "ThemeRotationAgent",
    "SECTOR_ROTATION_FINDING_TYPES",
    "SECTOR_ROTATION_SUBAGENTS",
    "THEME_ROTATION_FINDING_TYPES",
    "THEME_ROTATION_SUBAGENTS",
    "FLOW_PROXY_CAVEAT",
    "BROADENING_MIN_MEMBERS",
    # sensor agents (012G)
    "NewsFilingsAgent",
    "NEWS_FILINGS_FINDING_TYPES",
    "NEWS_FILINGS_SUBAGENTS",
    "FILING_FACT_FINDINGS",
    "COMPANY_CLAIM_FINDINGS",
    "claim_status_of",
    # sensor agents (012H)
    "SocialNarrativeAgent",
    "SOCIAL_NARRATIVE_FINDING_TYPES",
    "SOCIAL_NARRATIVE_SUBAGENTS",
    "assert_narrative_not_verified",
    # sensor agents (014D)
    "TechnicalRegimeAgent",
    "TECHNICAL_REGIME_FINDING_TYPES",
    "TECHNICAL_REGIME_SUBAGENTS",
    "TECHNICAL_SUBAGENT_REQUIRED_KEYS",
    "COMPRESSION_MAX_RANGE_PCT",
    "OVEREXTENSION_MIN_PCT",
    "VOLUME_CONFIRM_MULT",
    # sensor agents (014F)
    "MacroRegimeAgent",
    "MACRO_REGIME_FINDING_TYPES",
    "MACRO_REGIME_SUBAGENTS",
    "MACRO_SUBAGENT_REQUIRED_KEYS",
    "CustomerEvidenceAgent",
    "SupplierEvidenceAgent",
    "BottleneckEvidenceAgent",
    "LeadershipEvidenceAgent",
    "CUSTOMER_EVIDENCE_FINDING_TYPES",
    "SUPPLIER_EVIDENCE_FINDING_TYPES",
    "BOTTLENECK_EVIDENCE_FINDING_TYPES",
    "LEADERSHIP_EVIDENCE_FINDING_TYPES",
    "COMPANY_DOCUMENT_TEXT_EVENT_TYPES",
    "COMPANY_STATED_CAPACITY_GAP",
    "has_bottleneck_evidence_events",
    # forward scenario engine / sidecar (012I)
    "FORWARD_INPUT_NAMES",
    "SCENARIO_LABELS",
    "ForwardScenarioInput",
    "ForwardScenarioCase",
    "ForwardScenarioPacket",
    "ForwardMappedField",
    "ForwardSidecarMapping",
    "build_forward_scenario_packet",
    "to_nivesha_forward_sidecar",
    "run_nivesha_thesis_on_forward_sidecar",
    # data-quality / universe signal integration (012J)
    "build_pulse_data_quality_panel",
    "build_run_observability_panel",
    # manual/on-demand pulse orchestrator (012K)
    "run_pulse",
    "PulseResult",
    "PulseAgentRun",
    "DEFAULT_PULSE_FIXTURE_DIR",
    # runtime objects (013A)
    "PulseRun",
    "AgentRunContext",
    "AgentRunResult",
    "AgentHealthRecord",
    "ReplayRequest",
    "ReplayResult",
    "RUNTIME_OBJECTS",
    # runtime label vocabularies (013A)
    "RUN_MODES",
    "TRIGGER_TYPES",
    "ALLOWED_TRIGGER_TYPES",
    "RESERVED_TRIGGER_TYPES",
    "RUN_STATUSES",
    "DATA_QUALITY_STATUSES",
    "AGENT_RUN_STATUSES",
    "HEALTH_STATES",
    # runtime label helpers (013A)
    "is_run_mode",
    "is_trigger_type",
    "is_reserved_trigger_type",
    "is_run_status",
    "is_agent_run_status",
    "is_health_state",
    # append-only persistence stores (013B)
    "SCHEMA_VERSION",
    "CREDENTIAL_KEY_TOKENS",
    "FORBIDDEN_FIELD_TOKENS",
    "DQ_STATUSES",
    "DataQualityRecord",
    "AuditRecord",
    "AppendOnlyStore",
    "RunStore",
    "EventStore",
    "FindingStore",
    "SignalStore",
    "ThemePulseStore",
    "DataQualityStore",
    "AuditStore",
    "STORE_CLASSES",
    # deterministic replay harness (013C)
    "ReplayHarness",
    "ReplayReconstruction",
    # pulse persistence + observability glue (013F)
    "PULSE_FIXTURE_SOURCE_ID",
    "agent_results_from_pulse",
    "persist_and_summarize",
    # agent run ledger + failure-isolating runner (013D)
    "AgentRunLedger",
    "run_agent_isolated",
    "run_agents_isolated",
    "SkipAgent",
    "PolicyBlock",
    "POLICY_MESSAGE_TOKENS",
    # health / data-quality observability (013D)
    "SourceHealthRecord",
    "RunHealthSummary",
    "DataQualityRunSummary",
    "AgentHealthMonitor",
    "HEALTH_RECORDS",
    "CREDENTIALS_STATUSES",
    "RATE_LIMIT_STATUSES",
    # data-quality / security / policy gate runner (013E)
    "GATE_CATEGORIES",
    "GATE_STATUSES",
    "POLICY_OR_SECURITY_CATEGORIES",
    "REAL_DATA_MODES",
    "NETWORK_IMPORT_ROOTS",
    "SCHEDULER_BROKER_SOURCE_TOKENS",
    "SECRET_VALUE_PATTERNS",
    "FORBIDDEN_RECORD_FIELD_WORDS",
    "DataQualityGateResult",
    "SecurityGateResult",
    "PolicyGateResult",
    "DataQualityGateRunner",
    # typed capital-candidate contract + unforgeable eligibility gate (019B)
    "CANDIDATE_STATES",
    "INELIGIBLE_STATES",
    "FORWARD_SCENARIO_STATES",
    "TRUST_DATA_QUALITY_STATES",
    "CAPITAL_CANDIDATE_MODELS",
    "CapitalCandidate",
    "CapitalCandidateStore",
    "assess_candidate_eligibility",
    "blocked_candidates",
    "candidate_id_for",
    "eligible_candidates",
    "publish_candidates_for_run",
    "published_candidates",
    # source-adapter runtime + local market-data adapter (014A)
    "ADAPTER_RESULT_STATUSES",
    "ADAPTER_CREDENTIALS_STATUSES",
    "ADAPTER_RATE_LIMIT_STATUSES",
    "ADAPTER_FAILURE_MODES",
    "ADAPTER_SOURCE_HEALTH_LABELS",
    "SourceAdapterDescriptor",
    "SourceAdapterResult",
    "SourceAdapter",
    "deterministic_adapter_run_id",
    "source_health_from_result",
    "LOCAL_MARKET_DATA_ADAPTER_ID",
    "LOCAL_MARKET_DATA_DESCRIPTOR",
    "LOCAL_MARKET_DATA_DISCIPLINES",
    "LOCAL_MARKET_DATA_FILES",
    "STALE_AFTER_HOURS",
    "LocalMarketDataAdapter",
    # local macro-data adapter (014F)
    "LOCAL_MACRO_DATA_ADAPTER_ID",
    "LOCAL_MACRO_DATA_DESCRIPTOR",
    "LOCAL_MACRO_DATA_DISCIPLINES",
    "MACRO_READINGS_FILENAME",
    "MACRO_STALE_AFTER_HOURS",
    "LocalMacroDataAdapter",
    # local price-history adapter (014D)
    "LOCAL_PRICE_HISTORY_ADAPTER_ID",
    "LOCAL_PRICE_HISTORY_DESCRIPTOR",
    "LOCAL_PRICE_HISTORY_DISCIPLINES",
    "PRICE_HISTORY_FILE_SUFFIX",
    "PRICE_HISTORY_INDICATOR_UNITS",
    "PRICE_HISTORY_STALE_AFTER_HOURS",
    "LocalPriceHistoryAdapter",
    # SEC/FMP evidence adapter (014B)
    "SEC_FMP_EVIDENCE_ADAPTER_ID",
    "SEC_FMP_EVIDENCE_DESCRIPTOR",
    "SEC_FMP_EVIDENCE_DISCIPLINES",
    "SEC_TRANSPORT_KEYS",
    "FMP_TRANSPORT_KEYS",
    "FINANCIAL_INFLECTION_CONSUMER_GAP",
    "SecFmpEvidenceAdapter",
    # SEC EDGAR live filings adapter -- first production LIVE source (020B)
    "SEC_EDGAR_LIVE_ADAPTER_ID",
    "SEC_EDGAR_LIVE_DESCRIPTOR",
    "SEC_EDGAR_LIVE_DISCIPLINES",
    "SEC_EDGAR_LIVE_TRANSPORT_KEYS",
    "SEC_EDGAR_LIVE_EVENT_TYPES",
    "SEC_EDGAR_LIVE_RISK_EVENT_TYPES",
    "SEC_EDGAR_LIVE_MINIMUM_FORMS",
    "SEC_EDGAR_LIVE_FULL_BODY_FOLLOWUP_GAP",
    "SecEdgarLiveAdapter",
    # company IR documents adapter (014C)
    "COMPANY_DOCUMENTS_ADAPTER_ID",
    "COMPANY_DOCUMENTS_DESCRIPTOR",
    "COMPANY_DOCUMENTS_DISCIPLINES",
    "DESCRIPTOR_ONLY_CONSUMER_GAPS",
    "DOCUMENT_STALE_AFTER_DAYS",
    "IR_DECK_FILENAMES",
    "TAM_NOT_INDEPENDENTLY_VERIFIED_GAP",
    "TRANSCRIPT_FILE_PREFIX",
    "CompanyDocumentsAdapter",
    # X/social local-export adapter (014E)
    "SOCIAL_EXPORTS_ADAPTER_ID",
    "SOCIAL_EXPORTS_DESCRIPTOR",
    "SOCIAL_EXPORTS_DISCIPLINES",
    "SOCIAL_EXPORT_FILE_PREFIX",
    "SOCIAL_EXPORT_STALE_AFTER_HOURS",
    "SOCIAL_EXPORT_ACCOUNT_TYPES",
    "PROMOTER_BOT_RISK_VISIBLE_PCT",
    "SocialExportsAdapter",
    # pulse cadence core -- data + pure tick decision, never a daemon (015A)
    "ALL_POLICIES",
    "DEFAULT_CADENCE_POLICIES",
    "DEFAULT_MARKET_HOURS",
    "MAX_BACKOFF_MINUTES",
    "THROTTLE_WINDOW_MINUTES",
    "CadencePolicy",
    "MarketHoursCalendar",
    "PulseSchedule",
    "ScheduleState",
    "build_default_schedule",
    "state_for",
    "due_policies",
    "record_run",
    "pause",
    "resume",
    "throttled",
    "policy_to_dict",
    "policy_from_dict",
    "state_to_dict",
    "state_from_dict",
    "calendar_to_dict",
    "calendar_from_dict",
    "schedule_to_dict",
    "schedule_from_dict",
    # pulse orchestrator -- explicit-start scheduled-pulse runner, never a daemon (015B)
    "ORCHESTRATOR_ACTOR",
    "SCHEDULED_BY_POLICY_PREFIX",
    "PulseOrchestrator",
    "ScheduleStateStore",
    "Subscription",
    "TickResult",
    "append_schedule_state",
    "load_schedule_state",
    "run_due_pulses",
    "scheduled_policy_for",
    "subscription_from_dict",
    "subscription_to_dict",
    # diff-based alerts + append-only alert inbox -- observe, never execute (015C)
    "ALERT_CATEGORIES",
    "ALERT_SEVERITIES",
    "CATEGORY_SEVERITY",
    "Alert",
    "AlertAcknowledgment",
    "AlertAcknowledgmentStore",
    "AlertGenerationResult",
    "AlertStore",
    "acknowledge_alert",
    "acknowledged_alert_ids",
    "acknowledged_alerts",
    "alerts_with_status",
    "diff_persisted_runs",
    "generate_alerts_for_run",
    "previous_persisted_run_id",
    "record_failed_pulse_alert",
    "unacknowledged_alerts",
    "build_alert_inbox_panel",
    # shadow (non-production) alerts -- marked, review-tagged, severity-capped (020D)
    "SHADOW_MARKER",
    "SHADOW_MODE_VALUE",
    "RECOMMENDED_REVIEW_ACTIONS",
    "FORBIDDEN_ALERT_PHRASES",
    "run_dq_state",
    "to_shadow",
    "generate_shadow_alerts_for_run",
    # outcome learning -- append-only outcome records + label/count roll-ups (017A)
    "LEARNING_RECORDS",
    "LEARNING_STORE_CLASSES",
    "LEARNING_THRESHOLDS",
    "OUTCOME_LABELS",
    "RELIABILITY_LABELS",
    "RISK_CLAIM_STATES",
    "SUBJECT_KINDS",
    "LearningStore",
    "OutcomeRecord",
    "OutcomeStore",
    "OutcomeTracker",
    "SignalReliabilityRecord",
    "SourceReliabilityRecord",
    "ThemePulseAccuracyRecord",
    "emit_outcome_alerts",
    "persisted_run_ids",
    "record_learning_rollups",
    "record_outcomes",
    "roll_signal_reliability",
    "roll_source_reliability",
    "roll_theme_pulse_accuracy",
    "track_outcomes",
    # read-only portfolio intelligence -- bands / labels over the operator's
    # recorded holdings statement + the persisted stores (018A)
    "BAND_UNKNOWN",
    "CANDIDATE_COMPARISON_LABELS",
    "CONCENTRATION_BANDS",
    "CORRELATION_LABELS",
    "HOLDINGS_FILENAME",
    "HOLDINGS_FRESHNESS_LABELS",
    "HOLDINGS_RELPATH",
    "PORTFOLIO_DIRNAME",
    "PORTFOLIO_RECORDS",
    "PORTFOLIO_THRESHOLDS",
    "ROTATION_ALIGNMENT_LABELS",
    "STATE_ALIGNMENT",
    "CandidateComparison",
    "ConcentrationView",
    "ExposureView",
    "HoldingRecord",
    "PairCorrelationView",
    "PortfolioHoldings",
    "RotationAlignmentView",
    "band_for_position_weight",
    "band_for_theme_weight",
    "build_concentration",
    "build_correlation_labels",
    "build_exposure",
    "build_rotation_alignment",
    "compare_candidate",
    "load_holdings",
    "ticker_theme_map",
    # learning reviews -- thesis journal + postmortem / red-team / timing /
    # expert-account / archetype / experience records (017B)
    "JOURNAL_VERDICTS",
    "POSTMORTEM_LABELS",
    "REVIEW_RECORDS",
    "REVIEW_THRESHOLDS",
    "TIMING_CLAIMS",
    "TIMING_LABELS",
    "ArchetypeUpdate",
    "ExperienceLayerUpdate",
    "ExpertAccountReliabilityRecord",
    "RedTeamReview",
    "ThesisJournalEntry",
    "ThesisJournalStore",
    "ThesisPostmortem",
    "TimingReview",
    "append_experience_update",
    "journal_thesis",
    "review_red_team",
    "review_thesis",
    "review_timing",
    "roll_archetypes",
    "roll_expert_reliability",
]
